// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_project_as.Data;

#nullable disable

namespace Web_project_as.Migrations
{
    [DbContext(typeof(JewelryContext))]
    partial class JewelryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Price = 1200m,
                            ProductName = "Diamond Engagement Ring",
                            Quantity = 15
                        },
                        new
                        {
                            ProductID = 2,
                            Price = 450m,
                            ProductName = "Gold Chain Necklace",
                            Quantity = 10
                        },
                        new
                        {
                            ProductID = 3,
                            Price = 150m,
                            ProductName = "Silver Charm Bracelet",
                            Quantity = 20
                        },
                        new
                        {
                            ProductID = 4,
                            Price = 600m,
                            ProductName = "Classic Wedding Band",
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("Web_project_as.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            ProductID = 1,
                            Quantity = 3,
                            TotalPrice = 0m,
                            UserID = 1
                        },
                        new
                        {
                            OrderID = 2,
                            ProductID = 1,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 3,
                            ProductID = 2,
                            Quantity = 5,
                            TotalPrice = 0m,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("Web_project_as.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "lina@gmail.com",
                            FullName = "Lina",
                            Password = "123"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "sondos@gmail.com",
                            FullName = "Sondos Alqirim",
                            Password = "456"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "aya@gmail.com",
                            FullName = "Aya Alkirim",
                            Password = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
